import sys

with open('C:/Users/Moosa/Downloads/Project_Veritas/test_full_pipeline.py', 'r') as f:
    lines = f.readlines()

new_lines = []
in_build = False
for i, line in enumerate(lines):
    if line.startswith('def build_deal_context_live(ticker: str):'):
        in_build = True
        new_lines.append(line)
        new_lines.append('    """\n')
        new_lines.append('    Pulls REAL financial data using a Hybrid Architecture:\n')
        new_lines.append('    Primary: yfinance (quarterly sum)\n')
        new_lines.append('    Secondary: EDGAR (for future hardening)\n')
        new_lines.append('    Peers: CapIQ -> yfinance fallback\n')
        new_lines.append('    """\n')
        new_lines.append('    from project_veritas.tools.financials import get_financials_summary\n')
        new_lines.append('    from project_veritas.tools.peers import get_peer_multiples, calculate_premium_discount\n')
        new_lines.append('    from project_veritas.core.validation import validate_financials\n')
        new_lines.append('    from datetime import datetime\n\n')
        new_lines.append('    next_step("Pulling LIVE Data (yfinance + CapIQ)")\n\n')
        new_lines.append('    # 1. Fetch Financials\n')
        new_lines.append('    fin_data = get_financials_summary(ticker)\n')
        new_lines.append('    if not fin_data.get("revenue_ttm_M"):\n')
        new_lines.append('        print("    [ERROR] Could not fetch fundamental data.")\n')
        new_lines.append('        return {}\n\n')
        new_lines.append('    # Run Validation\n')
        new_lines.append('    val_report = validate_financials(fin_data)\n')
        new_lines.append('    val_report.print_summary()\n\n')
        new_lines.append('    # 2. Fetch Peers\n')
        new_lines.append('    industry = fin_data.get("industry", "Technology")\n')
        new_lines.append('    peers = get_peer_multiples(sector=industry, discovered_tickers=[], target_ticker=ticker, limit=4)\n\n')
        new_lines.append('    # 3. Calculate Premium/Discount\n')
        new_lines.append('    ev_ebitda = fin_data.get("ev_ebitda") or 0\n')
        new_lines.append('    premium_data = calculate_premium_discount(ev_ebitda, peers)\n\n')
        new_lines.append('    raw_fin = {\n')
        new_lines.append('        "market_cap_m": fin_data.get("market_cap_M"),\n')
        new_lines.append('        "total_debt_m": fin_data.get("net_debt_M"),\n')
        new_lines.append('        "total_cash_m": 0,\n')
        new_lines.append('        "reported_ebitda_m": fin_data.get("ebitda_reported_M"),\n')
        new_lines.append('        "net_income_m": 0,\n')
        new_lines.append('        "sbc_expense_m": fin_data.get("sbc_M")\n')
        new_lines.append('    }\n')
        new_lines.append('    next_step("Triggering RAG Math Agent")\n')
        new_lines.append('    math_res = run_math_agent(ticker, industry, raw_fin)\n')
        new_lines.append('    math_rationale = "Standard calculation."\n')
        new_lines.append('    wacc_pct = 9.5\n')
        new_lines.append('    if math_res:\n')
        new_lines.append('        wacc_pct = math_res.get("wacc_pct", wacc_pct)\n')
        new_lines.append('        math_rationale = math_res.get("rationale", "Standard calculation.")\n')
        new_lines.append('        print(f"    Math Agent Applied: {math_rationale}")\n')
        new_lines.append('        print(f"    Calculated WACC: {wacc_pct}%")\n\n')
        new_lines.append('    company_name = fin_data.get("ticker")\n')
        new_lines.append('    revenue_m = fin_data.get("revenue_ttm_M") or 0\n')
        new_lines.append('    adjusted_ebitda_m = fin_data.get("ebitda_adj_M") or 0\n')
        new_lines.append('    sbc_haircut_m = fin_data.get("sbc_M") or 0\n')
        new_lines.append('    ebitda_m = fin_data.get("ebitda_reported_M") or 0\n')
        new_lines.append('    fcf_margin = fin_data.get("fcf_margin_pct") or 0\n')
        new_lines.append('    current_market_ev = fin_data.get("enterprise_value_M") or 0\n')
        new_lines.append('    trading_mult = ev_ebitda\n\n')
        new_lines.append('    scenarios = {\n')
        new_lines.append('        "bear": round(current_market_ev * 0.75) if current_market_ev else 0,\n')
        new_lines.append('        "base": round(current_market_ev * 0.95) if current_market_ev else 0,\n')
        new_lines.append('        "bull": round(current_market_ev * 1.20) if current_market_ev else 0\n')
        new_lines.append('    }\n\n')
        new_lines.append('    deal_context = {\n')
        new_lines.append('        "company_name": company_name,\n')
        new_lines.append('        "ticker": ticker,\n')
        new_lines.append('        "sector": industry,\n')
        new_lines.append('        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),\n')
        new_lines.append('        "biz_intel": {\n')
        new_lines.append('            "company_name": company_name,\n')
        new_lines.append('            "sector": industry,\n')
        new_lines.append('            "market_cap_usd_m": fin_data.get("market_cap_M"),\n')
        new_lines.append('            "revenue_usd_m": revenue_m,\n')
        new_lines.append('            "yoy_revenue_growth": f"{round(fin_data.get(\'revenue_growth_pct\') or 0, 1)}%",\n')
        new_lines.append('            "gross_margin": "N/A",\n')
        new_lines.append('            "data_source": "yfinance (LIVE)"\n')
        new_lines.append('        },\n')
        new_lines.append('        "forensics": {\n')
        new_lines.append('            "forensic_score": 80,\n')
        new_lines.append('            "forensic_decomposition": {},\n')
        new_lines.append('            "quality_of_earnings": "MODERATE",\n')
        new_lines.append('            "reported_ebitda_usd_m": ebitda_m,\n')
        new_lines.append('            "adjusted_ebitda_usd_m": adjusted_ebitda_m,\n')
        new_lines.append('            "math_agent_rationale": math_rationale,\n')
        new_lines.append('            "ebitda_adjustment_pct": round((adjusted_ebitda_m - ebitda_m)/ebitda_m * 100, 1) if ebitda_m > 0 else 0,\n')
        new_lines.append('            "adjustments": [{"item": "SBC / Industry Adj", "value_m": sbc_haircut_m}],\n')
        new_lines.append('            "red_flags": [],\n')
        new_lines.append('            "green_flags": [],\n')
        new_lines.append('            "ocf_ni_ratio": 0,\n')
        new_lines.append('            "fcf_margin": round(fcf_margin, 1),\n')
        new_lines.append('            "debt_capacity_assessment": f"Net Debt: ${fin_data.get(\'net_debt_M\', 0):,}M"\n')
        new_lines.append('        },\n')
        new_lines.append('        "market_intel": {\n')
        new_lines.append('            "sector": industry,\n')
        new_lines.append('            "competitive_moat": "N/A",\n')
        new_lines.append('            "tam_sam_som": "N/A",\n')
        new_lines.append('            "current_trading_multiple": trading_mult,\n')
        new_lines.append('            "current_market_ev_m": current_market_ev,\n')
        new_lines.append('            "fair_value_ev_m": scenarios["base"],\n')
        new_lines.append('            "peer_comps": peers,\n')
        new_lines.append('            "implied_entry_multiple_range": f"{round(trading_mult * 0.8, 1)}-{round(trading_mult * 1.2, 1)}x" if trading_mult else "N/A"\n')
        new_lines.append('        },\n')
        new_lines.append('        "management": {\n')
        new_lines.append('            "management_score": 75,\n')
        new_lines.append('            "management_decomposition": {"vision": 30, "execution": 25, "governance": 20},\n')
        new_lines.append('            "promoter_background": "Loading...",\n')
        new_lines.append('            "governance_flags": [],\n')
        new_lines.append('            "succession_risk": "MEDIUM"\n')
        new_lines.append('        },\n')
        new_lines.append('        "valuation": {\n')
        new_lines.append('            "pe_decision": "PROCEED WITH CAUTION",\n')
        new_lines.append('            "do_not_exceed_ev_usd_m": scenarios["base"],\n')
        new_lines.append('            "scenarios": scenarios,\n')
        new_lines.append('            "wacc_pct": wacc_pct,\n')
        new_lines.append('            "convergence_quality": "MODERATE",\n')
        new_lines.append('            "key_risks": [\n')
        new_lines.append('                premium_data.get("narrative", "N/A"),\n')
        new_lines.append('                f"SBC Haircut of ${sbc_haircut_m:,.0f}M"\n')
        new_lines.append('            ],\n')
        new_lines.append('            "methods_used": ["Comparable Company", "DCF", "LBO"],\n')
        new_lines.append('            "sources_cited": ["yfinance (LIVE)", "Derived calculations"]\n')
        new_lines.append('        },\n')
        new_lines.append('        "data_integrity_warnings": [c.message for c in val_report.checks if not c.passed],\n')
        new_lines.append('        "financial_data": fin_data\n')
        new_lines.append('    }\n\n')
        new_lines.append('    print(f"\\n  Company:          {company_name}")\n')
        new_lines.append('    print(f"  Revenue (TTM):    ${revenue_m:,.0f}M (Growth: {deal_context[\'biz_intel\'][\'yoy_revenue_growth\']})")\n')
        new_lines.append('    print(f"  EBITDA (Rep):     ${ebitda_m:,.0f}M")\n')
        new_lines.append('    print(f"  SBC Haircut:     -${sbc_haircut_m:,.0f}M")\n')
        new_lines.append('    print(f"  EBITDA (Adj):     ${adjusted_ebitda_m:,.0f}M")\n')
        new_lines.append('    print(f"  FCF Margin:       {round(fcf_margin, 1)}%")\n')
        new_lines.append('    print(f"  Peer Comps:       {[p[\'ticker\'] for p in peers]}")\n\n')
        new_lines.append('    current_mkt_ev = current_market_ev\n')
        new_lines.append('    print(f"  Current Trading Multiple: {trading_mult:.1f}x (Market EV: ${current_mkt_ev:,.0f}M)")\n')
        new_lines.append('    fair_value_ev = scenarios["base"]\n')
        new_lines.append('    if adjusted_ebitda_m > 0:\n')
        new_lines.append('        print(f"  Fair Value Multiple: {fair_value_ev / adjusted_ebitda_m:.1f}x (Fair EV: ${fair_value_ev:,.0f}M)")\n')
        new_lines.append('        if current_mkt_ev > 0:\n')
        new_lines.append('            upside = ((fair_value_ev - current_mkt_ev) / current_mkt_ev) * 100\n')
        new_lines.append('            print(f"  Implied Upside: {upside:.1f}%")\n\n')
        new_lines.append('    return deal_context\n\n')
        continue
    if in_build:
        if line.startswith('def run_nvidia_debate'):
            in_build = False
            new_lines.append(line)
    else:
        new_lines.append(line)

with open('C:/Users/Moosa/Downloads/Project_Veritas/test_full_pipeline.py', 'w') as f:
    f.writelines(new_lines)
