INDUSTRY_TO_CAPIQ_FILE = {
    "Credit Services": "financials",
    "Capital Markets": "financials",
    "Banks - Diversified": "financials",
    "Banks - Regional": "financials",
    "Asset Management": "financials",
    "Financial Data & Stock Exchanges": "financials",
    "Semiconductors": "it",
    "Software - Application": "it",
    "Software - Infrastructure": "it",
    "Information Technology Services": "it",
    "Internet Retail": "consumer discretionary",
    "Internet Content & Information": "communication",
    "Drug Manufacturers - General": "healthcare",
    "Medical Devices": "healthcare",
    "Biotechnology": "healthcare",
    "Auto Manufacturers": "consumer discretionary",
    "Restaurants": "consumer discretionary",
    "Specialty Retail": "consumer discretionary",
    "Packaged Foods": "consumer staples",
    "Household & Personal Products": "consumer staples",
    "Aerospace & Defense": "industrials",
    "Oil & Gas Integrated": "energy",
    "Utilities - Regulated Electric": "utilities",
    "Real Estate Services": "real estate",
    "Specialty Chemicals": "materials",
}
